---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert -o config
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: redpanda-0
  name: redpanda-0
spec:
  ports:
    - name: "18081"
      port: 18081
      targetPort: 18081
    - name: "18082"
      port: 18082
      targetPort: 18082
    - name: "19092"
      port: 19092
      targetPort: 19092
    - name: "19644"
      port: 19644
      targetPort: 9644
  selector:
    io.kompose.service: redpanda-0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert -o config
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: redpanda-0
  name: redpanda-0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redpanda-0
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert -o config
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/krt-docker-network: "true"
        io.kompose.service: redpanda-0
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - chown -R 101:101 /var/lib/redpanda/data
          volumeMounts:
            - mountPath: /var/lib/redpanda/data
              name: redpanda-0
      containers:
        - args:
            - redpanda
            - start
            - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
            - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
            - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
            - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
            - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
            - --rpc-addr redpanda-0:33145
            - --advertise-rpc-addr redpanda-0:33145
            - --smp 1
            - --memory 1G
            - --mode dev-container
            - --default-log-level=debug
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.5
          name: redpanda-0
          ports:
            - containerPort: 18081
              hostPort: 18081
              protocol: TCP
            - containerPort: 18082
              hostPort: 18082
              protocol: TCP
            - containerPort: 19092
              hostPort: 19092
              protocol: TCP
            - containerPort: 9644
              hostPort: 19644
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/redpanda/data
              name: redpanda-0
      hostname: redpanda-0
      restartPolicy: Always
      volumes:
        - name: redpanda-0
          persistentVolumeClaim:
            claimName: redpanda-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redpanda-0
  name: redpanda-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  storageClassName: hostpath-csi

